apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-csi-driver-cluster-role-binding
  labels:
    app: spire-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-csi-driver-cluster-role
subjects:
  - kind: ServiceAccount
    name: spire-csi-driver
    namespace: spire-csi
