apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-csi-driver-config
  namespace: spire-csi
  labels:
    app: spire-csi
data:
  driver-config.yaml: |
    trustDomain: "spiffe-helper.local"
    agentSocketPath: "/run/spire/sockets/agent.sock"
    certFilePath: "/certs/svid.pem"
    keyFilePath: "/certs/svid.key"
    certsFilePath: "/certs/bundle.pem"
