apiVersion: v1
kind: Pod
metadata:
  name: spire-csi-example
  namespace: httpbin
spec:
  serviceAccountName: httpbin
  containers:
  - name: example
    image: alpine:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: spire-certs
      mountPath: /certs
      readOnly: true
  volumes:
  - name: spire-certs
    csi:
      driver: spire-csi
      volumeAttributes:
        spiffeID: "spiffe://spiffe-helper.local/ns/httpbin/sa/httpbin"
