apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: spiffe-helper
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 36443
nodes:
  - role: control-plane
    image: kindest/node:v1.28.15@sha256:a7bc0750242bc6916538c642e071e62f90a2908f0293322f7e71ba238d380720
  - role: worker
    image: kindest/node:v1.28.15@sha256:a7bc0750242bc6916538c642e071e62f90a2908f0293322f7e71ba238d380720
  - role: worker
    image: kindest/node:v1.28.15@sha256:a7bc0750242bc6916538c642e071e62f90a2908f0293322f7e71ba238d380720

