apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-registration-cluster-role-binding
  labels:
    app: spire-registration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-registration-cluster-role
subjects:
  - kind: ServiceAccount
    name: spire-registration
    namespace: spire-registration
